config/routes.rb
Homify::Application.routes.draw do
  root 'articles#index'

  devise_for :users

  resources :articles

  get 'tags/:tag', to: 'articles#index', as: :tag, constraints: { tag: /[^\/]+/ }

  match 'search', to: 'articles#index', as: 'search', via: %i(post get)
end

app/models/article.rb
# Article model
class Article < ActiveRecord::Base
  # Sort Order
  default_scope { order(created_at: :desc) }

  # Relations
  belongs_to :user
  has_many :taggings
  has_many :tags, through: :taggings

  # Validations
  validates :title, :description, presence: true

  # Methods
  # Class Methods
  def self.title_like(title)
    where("lower(articles.description) LIKE ?", "%#{title.downcase}%")
  end

  def self.description_like(description)
    where("lower(articles.description) LIKE ?", "%#{description.downcase}%")
  end

  # Instance Methods
  def tag_list
    tags.map(&:name).join(', ')
  end

  def tag_list=(names)
    self.tags = names.split(',').map do |name|
      Tag.where(name: name.strip).first_or_create!
    end
  end

  def self.tagged_with(name)
    tag = Tag.find_by(name: name)
    return nil unless tag

    tag.articles
  end
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  # Relations
  has_many :taggings
  has_many :articles, through: :taggings
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  # Relations
  belongs_to :tag
  belongs_to :article
  # belongs_to :taggable, polymorphic: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Validations
  validates_presence_of :email

  # Relations
  has_many :articles

  # Methods
  def user_name
    # TODO: Does the 'anonymous' can be changed to the email?
    name.present? ? name : 'Anonymous'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %w(show edit update destroy)
  before_action :check_if_user_logged_in, except: %w(index show)

  # GET /articles
  def index
    return @articles = Article.all unless params[:criteria]

    case params[:criteria].first
    when 'tag'
      @articles = Article.tagged_with(params[:terms])
    when 'title'
      @articles = Article.title_like(params[:terms])
    when 'description'
      @articles = Article.description_like(params[:terms])
    end
  end

  # GET /articles/1
  def show
    # Use find_by to not raise an exception if user is not found
    user = User.find_by(id: @article.user_id)
    @author_name = user.user_name if user
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
    unless current_user.id == @article.user_id
      redirect_to root_url, flash: { errors: 'You are not authorized to edit this!' }
    end
  end

  # POST /articles
  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article, notice: 'Article was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /articles/1
  def update
    if @article.update(article_params)
      redirect_to @article, notice: 'Article was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /articles/1
  def destroy
    @article.destroy
    redirect_to articles_url, notice: 'Article was successfully destroyed.'
  end

  private

  def check_if_user_logged_in
    # Gaurd clause to check if user is not yet logged in
    redirect_to new_user_session_path, flash: { errors: 'Please login first!' } unless user_signed_in?
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_article
    @article = Article.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def article_params
    params.require(:article).permit(:title, :description, :user_id, :tag_list)
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: [:show, :edit, :update, :destroy]

  # GET /tags
  def index
    @tags = Tag.all
  end

  # GET /tags/1
  def show
  end

  # GET /tags/new
  def new
    @tag = Tag.new
  end

  # GET /tags/1/edit
  def edit
  end

  # POST /tags
  def create
    @tag = Tag.new(tag_params)

    if @tag.save
      redirect_to @tag, notice: 'Tag was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /tags/1
  def update
    if @tag.update(tag_params)
      redirect_to @tag, notice: 'Tag was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /tags/1
  def destroy
    @tag.destroy
    redirect_to tags_url, notice: 'Tag was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tag
      @tag = Tag.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def tag_params
      params.require(:tag).permit(:name)
    end
end

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :tag_list, 'Tags (separated by commas)' %><br />
    <%= f.text_field :tag_list %>
  </div>

  <div class="form-group">
    <%= f.hidden_field :user_id, value: current_user.id %>
  </div>

  <div class="form-group">
    <%= f.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<p id="notice"><%= notice if current_page? articles_path %></p>

<h1>Magazine Articles</h1>

<br />

<div class="container">
  <div class="row row-margin-bottom">
    <%= form_tag search_path do %>
    <div class="form-group">
      <label class="radio-inline">
        <%= radio_button 'criteria', '', 'tag', checked: true %> Tag
      </label>
      <label class="radio-inline">
        <%= radio_button 'criteria', '', 'title' %> Title
      </label>
      <label class="radio-inline">
        <%= radio_button 'criteria', '', 'description' %> Description
      </label>
    </div>

    <div class="form-group">
      <div class="input-group input-group-sm">
        <%= text_field_tag(:terms, params['search_box'], class: 'form-control') %>
        <span class="input-group-btn">
          <%= submit_tag 'Search', class: 'btn btn-default' %>
        </span>
      </div>
    </div>
    <% end %>
  </div>

  <% if @articles.present? %>
    <div class="row row-margin-bottom">
      <% @articles.each do |article| %>
      <div class="col-md-4 no-padding lib-item" data-category="view">
        <div class="lib-panel">
          <div class="row box-shadow">
            <div class="col-md-6">
              <img class="lib-img-show" src="http://lorempixel.com/850/850/?random=<%= SecureRandom.random_number(1000) %>">
            </div>
            <div class="col-md-6">
              <div class="lib-row lib-header">
                <%= link_to article.title, article %>
                <div class="lib-header-seperator"></div>
              </div>
              <div class="lib-row lib-desc">
                <%= truncate article.description, length: 140 %>
                <div class="lib-header-seperator"></div>
              </div>
              <br />
              <div class="lib-row">
                Tags: <%= raw article.tags.map(&:name).map { |t| link_to t, tag_path(t) }.join(', ') %>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-1"></div>
      <% end %>
    </div>
  <% end %>

  <div class="form-group">
    <%= link_to 'New Article', new_article_path, class: 'btn btn-default form-control' %>
  </div>
</div>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @article.description %>
</p>

<p>
  <strong>Author:</strong>
  <%= @author_name %>
</p>

<p>
  <strong>Tags:</strong>
  <%= raw @article.tags.map(&:name).map { |t| link_to t, tag_path(t) }.join(', ') %>
</p>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

app/views/layouts/_footer.html.erb
<div id="footer">
  <div class="container">

    <div class="row footer-first-row">

      <div class="col-xs-12 text-center">
        <p><small>
          &copy; <%= Time.now.year %> - Islam Wazery
          <br/>
          <%= link_to 'GitHub', 'http://www.github.com/wazery' %>
        </small></p>
      </div>

    </div>

  </div>
</div>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
<% if msg.is_a?(String) %>
<div class="alert alert-<%= name == "notice" ? "success" : "danger" %>">
  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
  <%= content_tag :div, msg, :id => "flash_#{name}" %>
</div>
<% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
			<%= link_to 'Homify Magazine', root_url, class: 'navbar-brand' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active">
        <%= link_to root_path, class: 'nav-link' do %>
          <span class="sr-only">(current)</span>
        <% end %>
        </li>

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
        <% else %>
            <li><%= link_to 'Login', new_user_session_path %></li>
            <li><%= link_to 'Sign Up', new_user_registration_path %></li>
        <% end %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
  <title><%= @title || 'Magazine App' %></title>
  <%= favicon_link_tag 'favicon.ico' %>
  <%= favicon_link_tag 'apple-touch-icon.png', rel: 'apple-touch-icon', type: 'image/png' %>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="wrap">
    <header>
      <%= render 'layouts/navigation' %>
    </header>

    <div class="container">

      <div class="row">
        <div class="col-sm-6 col-sm-offset-3 text-center">
          <%= render 'layouts/messages' %>
        </div>
      </div>

      <div class="row">
        <div class="col-lg-12">
          <%= yield %>
        </div>
      </div>

    </div>
  </div>

  <%= render 'layouts/footer' %>

</body>
</html>